UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Models/EnrollStudentInCourse.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManagmentSystem.Models
{
    public class EnrollStudentInCourse
    {
        public int Id { get; set; }
        [DisplayName("Registration No")]
        public int StudentId { get; set; }

        public string Name { get; set; }
        public string Email { get; set; }
        [DisplayName("Department")]
        public int DepartmentId { get; set; }
        [DisplayName("Course")]
        public int CourseId { get; set; }
        [Required(ErrorMessage = "Date is required!")]
        [DataType(DataType.Date)]
        public DateTime EnrollDate { get; set; }

        public bool Status { get; set; }
    }
}

UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Controllers/EnrollStudentInCourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagmentSystem.Manager;
using UniversityManagmentSystem.Models;

namespace UniversityManagmentSystem.Controllers
{
    public class EnrollStudentInCourseController : Controller
    {
        StudentManager studentManager = new StudentManager();
        CourseManager courseManager = new CourseManager();

        [HttpGet]
        public ActionResult Enroll()
        {
            IEnumerable<Student> students = studentManager.GetAll;
            IEnumerable<Course> courses = courseManager.GetAll;
            ViewBag.Students = students;
            ViewBag.Courses = courses;
            return View();
        }
        [HttpPost]
        public ActionResult Enroll(EnrollStudentInCourse enrollStudent)
        {
            string message;
            try
            {
                message = studentManager.Save(enrollStudent);
                ViewBag.Message = message;
                IEnumerable<Student> students = studentManager.GetAll;
                IEnumerable<Course> courses = courseManager.GetAll;
                ViewBag.Students = students;
                ViewBag.Courses = courses;

                return View();
            }
            catch (Exception exception)
            {

                message = exception.InnerException.Message;
                ViewBag.Message = message;
                return View();
            }
        }

        public JsonResult GetStudentById(int studentId)
        {
            StudentViewModel student = studentManager.GetStudentInformationById(studentId);
            return Json(student, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCourseByStudentId(int studentId)
        {
            Student aStudent = studentManager.GetAll.ToList().Find(st => st.Id == studentId);
            IEnumerable<Course> courses = courseManager.GetAll.ToList().FindAll(d => d.DepartmentId == aStudent.DepartmentId);
            return Json(courses, JsonRequestBehavior.AllowGet);

        }

    }
}

UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Views/EnrollStudentInCourse/Enroll.cshtml
@*@using System.Globalization*@
@model  UniversityManagmentSystem.Models.EnrollStudentInCourse
@{
    ViewBag.Title = "Enroll";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
    <link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.16/themes/humanity/jquery-ui.css"
          rel="stylesheet" type="text/css" />
}

<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Enroll In a Course</h3>
                    </div>
                    <div class="box-body">
                        <!-- form start -->
                        <form id="enrollCourse" method="post" class="form-horizontal">
                            <div class=" form-group">
                                <label for="StudentId" class="col-sm-3 control-label">Registration No</label>
                                <div class="col-sm-6">
                                    <select id="StudentId" name="StudentId" class="form-control">
                                        <option value="">---Select---</option>
                                        @foreach (var student in ViewBag.Students)
                                        {
                                            <option value="@student.Id">@student.RegNo</option>
                                        }
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="Name" class="col-sm-3 control-label">Name</label>
                                <div class="col-sm-6">
                                    <input type="text" class="form-control" id="Name" readonly="readonly" name="Name" placeholder="This Field Is Read Only" disabled>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Email" class="col-sm-3 control-label">Email</label>
                                <div class="col-sm-6">
                                    <input type="text" class="form-control" id="Email" readonly="readonly" name="Email" placeholder="This Field Is Read Only" disabled>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class=" form-group">
                                <label for="DepartmentId" class="col-sm-3 control-label">Department</label>
                                <div class="col-sm-6">
                                    <input type="text" class="form-control" id="DepartmentId" name="DepartmentId" readonly="readonly" placeholder="This Field Is Read Only" disabled />
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="CourseId" class="col-sm-3 control-label">Course</label>
                                <div class="col-sm-6">
                                    <select id="CourseId" name="CourseId" class="form-control">
                                        <option value="">---Select---</option>
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="EnrollDate" class="col-sm-3 control-label">Date</label>
                                <div class="col-sm-6">
                                    <input type="text" class="form-control" id="EnrollDate" name="EnrollDate" value="@DateTime.Now.ToShortDateString()">
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-3"></div>
                                <div class="col-sm-6">
                                    <button type="submit" class="btn btn-info pull-left">Enroll </button>
                                </div>
                                <div class="col-sm-3"></div>
                            </div>
                        </form>
                    </div> 
                    <div class="box-footer">
                        @if (ViewBag.Message != null)
                        {
                            <p style="font-size: 20px; color: blue">@ViewBag.Message</p>
                        }
                    </div>

                </div>

            </div>

        </div>

    </section>

</div>


@section scripts{
    <script src="~/TextBoxCalander/jquery-1.7.js" type="text/javascript"></script>
    <script src="~/TextBoxCalander/jquery-ui.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script>
            $(document).ready(function () {
 
                $("#enrollCourse").validate({
                    rules: {
                        StudentId: "required",
                        CourseId: "required",
                        EnrollDate:"required"
                    },
                    messages: {
                        StudentId:"Please select student Registration No",
                        CourseId: "Please select Course",
                        EnrollDate:"Select the Date"
                    }
                });

                $("#StudentId").change(function () {
                    var stId = $("#StudentId").val();
                    $("#CourseId").empty();
                    $("#CourseId").append('<option value=' + "" + '>--Select--</option>');
                    var json = { studentId: stId };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetStudentById", "EnrollStudentInCourse")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {
                            //alert(data);

                            var name = data.Name;
                            var email = data.Email;
                            var dept = data.Department;
                            $("#Name").val(name);
                            $("#Email").val(email);
                            $("#DepartmentId").val(dept);
                        }
                    });


                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetCourseByStudentId", "EnrollStudentInCourse")',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {


                            $.each(data, function (key, value) {
                                $("#CourseId").append('<option value=' + value.Id + '>' + value.Name + '</option>');

                            });
                        }
                    });

                });
                //$("[id$=EnrollDate]").datepicker();
                //$("#EnrollDate").datepicker({
                //    autoclose: true
                //});

                $(function () {
                    $("#EnrollDate").datepicker();
                });

            });
    </script>
}