UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Models/StudentResult.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManagmentSystem.Models
{
    public class StudentResult
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Please select a student Registration No!")]
        [DisplayName("Student Reg No.")]
        public int StudentId { get; set; }

        public string Name { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }

        public int CourseId { get; set; }

        public string Grade { get; set; }
        public bool Status { get; set; }
    }
}

UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Models/StudentResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UniversityManagmentSystem.Models
{
    public class StudentResultViewModel
    {
        public int StudentId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Grade { get; set; }
    }
}

UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Controllers/StudentResultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagmentSystem.Manager;
using UniversityManagmentSystem.Models;

namespace UniversityManagmentSystem.Controllers
{
    public class StudentResultController : Controller
    {
        StudentManager _studentManager = new StudentManager();
        CourseManager _courseManager = new CourseManager();

        // GET: /StudentResult/Create
        public ActionResult Save()
        {
            IEnumerable<Student> students = _studentManager.GetAll;
            IEnumerable<Course> courses = _courseManager.GetAll;
            ViewBag.Students = students;
            ViewBag.Courses = courses;
            return View();
        }

        //
        // POST: /StudentResult/Create
        [HttpPost]
        public ActionResult Save(StudentResult studentResult)
        {
            try
            {
                ViewBag.Message = _studentManager.Save(studentResult);
                IEnumerable<Student> students = _studentManager.GetAll;
                IEnumerable<Course> courses = _courseManager.GetAll;
                ViewBag.Students = students;
                ViewBag.Courses = courses;

                return View();
            }
            catch (Exception exception)
            {
                ViewBag.Message = exception.InnerException.Message;
                return View();
            }
        }


        public JsonResult GetStudentById(int studentId)
        {
            StudentViewModel student = _studentManager.GetStudentInformationById(studentId);
            return Json(student, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCoursesTakebByStudent(int studentId)
        {
            IEnumerable<Course> courses = _courseManager.GetCoursesTakenByaStudentById(studentId);
            return Json(courses, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult ViewStudentResult()
        {
            IEnumerable<Student> students = _studentManager.GetAll;
            ViewBag.Students = students;
            return View();
        }

        public JsonResult GetStudentResultByStudentId(int studentId)
        {
            IEnumerable<StudentResultViewModel> studentResults = _studentManager.GetStudentResultByStudentId(studentId);
            return Json(studentResults, JsonRequestBehavior.AllowGet);
        }


    }
}

UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Views/StudentResult/Save.cshtml
@{
    ViewBag.Title = "Student Result";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
}

<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Student Result</h3>
                    </div>
                    <div class="box-body">
                        <!-- form start -->
                        <form id="saveStudentResult" method="post" class="form-horizontal">
                            <div class=" form-group">
                                <label for="StudentId" class="col-sm-3 control-label">Student Reg. No</label>
                                <div class="col-sm-6">
                                    <select id="StudentId" name="StudentId" class="form-control">
                                        <option value="">---Select---</option>
                                        @foreach (var student in ViewBag.Students)
                                        {
                                            <option value="@student.Id">@student.RegNo</option>
                                        }
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class=" form-group">
                                <label for="Name" class="col-sm-3 control-label">Name</label>
                                <div class="col-sm-6">
                                    <input type="text" id="Name" class="form-control" name="Name" readonly="readonly" />
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Email" class="col-sm-3 control-label">Email</label>
                                <div class="col-sm-6">
                                    <input type="text" id="Email" class="form-control" name="Email" readonly="readonly" />
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Department" class="col-sm-3 control-label">Department</label>
                                <div class="col-sm-6">
                                    <input type="text" id="Department" class="form-control" name="Department" readonly="readonly" />
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class=" form-group">
                                <label for="CourseId" class="col-sm-3 control-label">Course</label>
                                <div class="col-sm-6">
                                    <select id="CourseId" name="CourseId" class="form-control">
                                        <option value="">---Select Course---</option>
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Grade" class="col-sm-3 control-label">Select Grade Letter</label>
                                <div class="col-sm-6">
                                    <select id="Grade" name="Grade" class="form-control">
                                        <option value="">Select Grade</option>
                                        <option value="A+">A+</option>
                                        <option value="A">A</option>
                                        <option value="A-">A-</option>
                                        <option value="B+">B+</option>
                                        <option value="B">B</option>
                                        <option value="B-">B-</option>
                                        <option value="C+">C+</option>
                                        <option value="C">C</option>
                                        <option value="C-">C-</option>
                                        <option value="D+">D+</option>
                                        <option value="D">D</option>
                                        <option value="D-">D-</option>
                                        <option value="F">F</option>
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-3"></div>
                                <div class="col-sm-6">
                                    <button type="submit" class="btn btn-info pull-left">Save</button>
                                </div>
                                <div class="col-sm-3"></div>
                            </div>
                        </form>
                    </div>                      <!-- /.box-body -->
                    <div class="box-footer">
                        @if (ViewBag.Message != null)
                        {
                            <p style="font-size: 20px; color: blue">@ViewBag.Message</p>
                        }
                    </div>
                    <!-- /.box-footer -->
                    <!-- form end -->
                </div>
                <!-- /.box -->
            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@section scripts{

    <script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function () {
            $("#saveStudentResult").validate({
                rules: {
                    StudentId: "required",
                    CourseId: "required",
                    Grade: "required"
                },
                messages: {
                    StudentId: "Please select the student reg no",
                    CourseId: "Please select a course",
                    Grade:"Please select grade"
                }
            });

            $("#StudentId").change(function () {
                var stId = $("#StudentId").val();
                $("#CourseId").empty();
                $("#CourseId").append('<option value="">---Select Course---</option>');

                var json = { studentId: stId };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentById", "StudentResult")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        var name = data.Name;
                        var email = data.Email;
                        var dept = data.Department;
                        $("#Name").val(name);
                        $("#Email").val(email);
                        $("#Department").val(dept);
                    }
                });


                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCoursesTakebByStudent", "StudentResult")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        $.each(data, function (key, value) {

                            $("#CourseId").append('<option value=' + value.Id + '>' + value.Name + '</option>');

                        });
                    }
                });

            });

        });
    </script>
}

UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Views/StudentResult/ViewStudentResult.cshtml
@{
    ViewBag.Title = "ViewStudentResult";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
}
<script language="javascript">

    function myPrint() {
        var myPrintContent = document.getElementById('printDIV');
        var myPrintWindow = window.open('left=300,top=100,width=400,height=400');
        myPrintWindow.document.write(myPrintContent.innerHTML);
        myPrintWindow.document.getElementById('hiddenDiv').style.display = 'block';
        myPrintWindow.document.close();
        myPrintWindow.focus();
        myPrintWindow.print();
        myPrintWindow.close();
        return false;
    }
</script>
@*https://stackoverflow.com/questions/25704040/print-contents-of-a-hidden-div*@
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
       
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">View Student Result</h3>
                    </div>
                    <div class="box-body">
                        <!-- form start -->
                        <form id="viewStudentResult" class="form-horizontal">
                            <div class=" form-group">
                                <label for="StudentId" class="col-sm-3 control-label">Student Reg. No</label>
                                <div class="col-sm-6">
                                    <select id="StudentId" name="StudentId" class="form-control">
                                        <option value="">---Select---</option>
                                        @foreach (var student in ViewBag.Students)
                                        {
                                            <option value="@student.Id">@student.RegNo</option>
                                        }
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class=" form-group">
                                <label for="Name" class="col-sm-3 control-label">Name</label>
                                <div class="col-sm-6">
                                    <input type="text" id="Name" class="form-control" name="Name" readonly="readonly" disabled />
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Email" class="col-sm-3 control-label">Email</label>
                                <div class="col-sm-6">
                                    <input type="text" id="Email" class="form-control" name="Email" readonly="readonly" disabled />
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Department" class="col-sm-3 control-label">Department</label>
                                <div class="col-sm-6">
                                    <input type="text" id="Department" class="form-control" name="Department" readonly="readonly" disabled />
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-3"></div>
                                <div class="col-sm-6">
                                    <input type="submit" class="btn btn-info pull-left" value="Make PDF" onclick="myPrint();" />
                                </div>
                            </div>
                        </form>
                        <!-- form end -->
                    </div> 
                    <!-- /.box-body -->

                    <div id="studenRsult" class="box-footer">
                        <table id="resultData" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Serial</th>
                                    <th>Code</th>
                                    <th>Name</th>
                                    <th>Grade</th>
                                </tr>
                            </thead>
                            <tbody id="myData"></tbody>
                        </table>

                        <div id="printDIV">
                            <div id="hiddenDiv" style="display: none">
                                <!-- title row -->
                                <div class="row" align="center">
                                    <div class="col-xs-12">
                                        <table class="page-header" width="100%" style="margin-bottom: 25px;">
                                            <tr>
                                                <td><img src="~/ContentHome/Account/img/logouu.jpg" alt="UniversityLogo" style="width: 120px; height: 90px;" /></td>
                                                <td>
                                                    <h2>Uttara University</h2>
                                                    <b>Uttara, Dhaka</b>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>
                                <!-- info row -->
                                <p class="text-muted well well-sm no-shadow" style="margin-top: 10px; text-align: center; text-decoration: underline; text-transform: uppercase; font-weight: bold;">Academic Transcript</p>
                                <div class="row">

                                    <div class="col-xs-6">
                                        <div class="table-responsive">
                                            <table class="table border-info">
                                                <tr>
                                                    <th style="width: 50%; text-align: left; text-decoration: underline;">Student Details:</th>
                                                </tr>
                                                <tr>
                                                    <th style="text-align: right;">Name:</th>
                                                    <td><label id="printName" style="font-weight: bold;"></label></td>
                                                </tr>
                                                <tr>
                                                    <th style="text-align: right;">Email:</th>
                                                    <td><label id="printEmail"></label></td>
                                                </tr>
                                                <tr>
                                                    <th style="text-align: right;">Department:</th>
                                                    <td><label id="printDepartment"></label></td>
                                                </tr>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="col-xs-6">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-12 table-responsive">
                                        <p style="text-align: left; text-decoration: underline;">Result Details:</p>
                                        <table class="table table-bordered" style="border: 1px solid black; width: 100%; border-collapse: collapse; margin-bottom: 100px;">
                                            <thead>
                                            <tr>
                                                <th style="border: 1px solid black;">Serial</th>
                                                <th style="border: 1px solid black;">Course Code</th>
                                                <th style="border: 1px solid black;">Student Name</th>
                                                <th style="border: 1px solid black;">Grade</th>
                                            </tr>
                                            </thead>
                                            <tbody id="myDataPrint"></tbody>
                                        </table>
                                    </div>
                                    <!-- /.col -->
                                </div>
                                <!-- /.row -->
                                
                                <div class="row">
                                    <div class="col-xs-12 table-responsive">
                                        <table width="100%">
                                            <tr>
                                                <td>
                                                    <p style="text-align: left;">Result Publication Date : @DateTime.Now.ToString("dd-MMM-yyyy")</p>
                                                </td>
                                                <td><h4 style="text-align: right;">Controller of Examination</h4></td>
                                            </tr>
                                        </table>
                                    </div>
                                    <!-- /.col -->
                                </div>
                                <!-- /.row -->
                            </div>
                        </div>
                        <!-- /.print div -->

                    </div>
                    <!-- /.box-footer -->
                </div>
                <!-- /.box -->
            </div>
            <!--/.col (left) -->
            <div class="col-md-12 table-responsive">
                
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->

@section scripts{

    <script>
        $(document).ready(function () {
            $("#resultData").hide();

            $("#StudentId").change(function () {
                var stId = $("#StudentId").val();

                

                $("#myData").empty();
                var json = { studentId: stId };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentById", "StudentResult")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {

                        var name = data.Name;
                        var email = data.Email;
                        var dept = data.Department;
                        $("#Name").val(name);
                        $("#Email").val(email);
                        $("#Department").val(dept);

                        $("#printName").text(name);
                        $("#printEmail").text(email);
                        $("#printDepartment").text(dept);
                        
                    }
                });


                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetStudentResultByStudentId", "StudentResult")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {

                        $("#myData").empty();
                        $("#myDataPrint").empty();

                        $.each(data, function (index, value) {
                            
                            if (index <= 1)
                            {
                            index++;
                            $("#resultData").show();
                            var row = $("<tr><td>" + index+ "</td><td>" + value.Code + "</td><td>" + value.Name + "</td><td>" + value.Grade + "</td></tr>");
                            $("#myData").append(row);
                                    
                            var row2 = $("<tr><td style='border: 1px solid black; padding: 5px 10px; text-align: center;'>" + index + "</td><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Code + "</td><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Name + "</td><td style='border: 1px solid black; padding: 5px 10px;'>" + value.Grade + "</td></tr>");
                            $("#myDataPrint").append(row2);
                            }
                        });
                    }
                });

            });

        });
    </script>
}