UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Models/CourseAssignToTeacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManagmentSystem.Models
{
    public class CourseAssignToTeacher
    {
        public int Id { get; set; }
        [DisplayName("Department")]
        [Required]
        public int DepartmentId { get; set; }
        [DisplayName("Teacher")]
        [Required]
        public int TeacherId { get; set; }
        [DisplayName("Credit To be Taken")]
        public float CreditTobeTaken { get; set; }
        [Required]
        [DisplayName("Remaining Credit")]
        public float CreditTaken { get; set; }
        [Required]
        [DisplayName("Course")]
        public int CourseId { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public float Credit { get; set; }
        public bool Status { get; set; }
    }
}

UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Controllers/CourseAssignToTeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagmentSystem.Manager;
using UniversityManagmentSystem.Models;

namespace UniversityManagmentSystem.Controllers
{
    public class CourseAssignToTeacherController : Controller
    {
        CourseManager _courseManger = new CourseManager();
        DepartmentManager _departmentManager = new DepartmentManager();
        TeacherManager _teacherManager = new TeacherManager();
        CourseAssignToTeacherManager courseAssignToTeacherManager = new CourseAssignToTeacherManager();
        //
        // GET: /CourseAssignToTeacher/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AssignCourseToTeacher()
        {
            IEnumerable<Course> courses = _courseManger.GetAll;
            IEnumerable<Department> departments = _departmentManager.GetAll();
            IEnumerable<Teacher> teachers = _teacherManager.GetAll();
            ViewBag.Courses = courses;
            ViewBag.Departments = departments;
            ViewBag.Teachers = teachers;
            return View();
        }
        [HttpPost]
        public ActionResult AssignCourseToTeacher(CourseAssignToTeacher courseAssign)
        {
            try
            {
                ViewBag.Message = courseAssignToTeacherManager.Save(courseAssign);
                IEnumerable<Course> courses = _courseManger.GetAll;
                IEnumerable<Department> departments = _departmentManager.GetAll();
                IEnumerable<Teacher> teachers = _teacherManager.GetAll();
                ViewBag.Courses = courses;
                ViewBag.Departments = departments;
                ViewBag.Teachers = teachers;
                return View();
            }
            catch (Exception exception)
            {

                ViewBag.Message = exception.InnerException.Message;
                return View();
            }
        }
        public JsonResult GetCourseInformationByDepartmentId(int departmentId)
        {
            IEnumerable<CourseViewModel> courseViewModels = _courseManger.GetCourseViewModels.ToList().FindAll(deptId => deptId.DepartmentId == departmentId);
            return Json(courseViewModels, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetTeachersByDepartmentId(int departmentId)
        {
            IEnumerable<Teacher> teachers = _teacherManager.GetAll();
            var teacherList = teachers.ToList().FindAll(t => t.DepartmentId == departmentId);
            return Json(teacherList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCoursesByDepartmentId(int departmentId)
        {
            IEnumerable<Course> courses = _courseManger.GetAll;
            var courseList = courses.ToList().FindAll(c => c.DepartmentId == departmentId);
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetTeacherById(int teacherId)
        {
            IEnumerable<Teacher> teachers = _teacherManager.GetAll();
            Teacher aTeacher = teachers.ToList().Find(t => t.Id == teacherId);
            return Json(aTeacher, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCourseById(int courseId)
        {
            IEnumerable<Course> courses = _courseManger.GetAll;
            Course aCourse = courses.ToList().Find(c => c.Id == courseId);
            return Json(aCourse, JsonRequestBehavior.AllowGet);
        }
	}
}

UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Views/CourseAssignToTeacher/AssignCourseToTeacher.cshtml
@{
    ViewBag.Title = "AssignCourseToTeacher";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
}

<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Course Assign To Teacher</h3>
                    </div>
                    <div class="box-body">
                        <!-- form start -->
                        <form id="courseAssignToteacher" method="post" class="form-horizontal">
                            <div class=" form-group">
                                <label for="DepartmentId" class="col-sm-3 control-label">Department</label>
                                <div class="col-sm-6">
                                    <select id="DepartmentId" name="DepartmentId" class="form-control">
                                        <option value="">---Select Department---</option>
                                        @foreach (var dept in ViewBag.Departments)
                                        {
                                            <option value="@dept.Id">@dept.Name</option>
                                        }
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class=" form-group">
                                <label for="TeacherId" class="col-sm-3 control-label">Teacher</label>
                                <div class="col-sm-6">
                                    <select id="TeacherId" name="TeacherId" class="form-control">
                                        <option value="">---Select Teacher---</option>
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="CreditTobeTaken" class="col-sm-3 control-label">Credit To be Taken</label>
                                <div class="col-sm-6">
                                    <input class="form-control" id="CreditTobeTaken" name="CreditTobeTaken" readonly="readonly" placeholder="This field is read only ">
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="CreditTaken" class="col-sm-3 control-label">Remaing Credit</label>
                                <div class="col-sm-6">
                                    <input type="text" class="form-control" id="CreditTaken" name="CreditTaken" readonly="readonly" placeholder="This field is read only ">
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class=" form-group">
                                <label for="CourseId" class="col-sm-3 control-label">Course</label>
                                <div class="col-sm-6">
                                    <select id="CourseId" name="CourseId" class="form-control">
                                        <option value="">---Select Course---</option>
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Name" class="col-sm-3 control-label">Name</label>
                                <div class="col-sm-6">
                                    <input type="text" id="Name" class="form-control" name="Name" readonly="readonly" placeholder="This field is read only " />
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="Credit" class="col-sm-3 control-label">Credit</label>
                                <div class="col-sm-6">
                                    <input type="text" id="Credit" class="form-control" name="Credit" readonly="readonly" placeholder="This field is read only " />
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-3"></div>
                                <div class="col-sm-6">
                                    <button type="submit" id="submitButton" class="btn btn-info pull-left">Save</button>
                                </div>
                                <div class="col-sm-3"></div>
                            </div>
                    </form>
                </div>                      <!-- /.box-body -->
                    <div class="box-footer">
                        <p>@Html.ActionLink("View Course Static", "ShowCourseStatics","CourseView")</p>
                        @if (ViewBag.Message != null)
                        {
                            <p style="font-size: 20px; color: blue">@ViewBag.Message</p>
                        }
                    </div>
                    <!-- /.box-footer -->
                    <!-- form end -->
                </div>
                <!-- /.box -->
            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@section Scripts {

    <script src="~/Scripts/jquery.validate.js"></script>

    <script>
    $(document).ready(function () {
        $('#submitButton').click(function () {
            var val1 = parseFloat($('#CreditTaken').val());
            var val2 = parseFloat($('#Credit').val());
            var val = val1 - val2;
            if (val < 0) {
                var flag = confirm('Remaining credit is ' + val + '. Are you sure, you want to assign more credit?');
                if (flag == false)
                    return false;
            }
            return true;
        });

        $("#courseAssignToteacher").validate({
            rules: {

                TeacherId: "required",

                DepartmentId: "required",
                CourseId: "required"
                },
            messages: {

                TeacherId: "Please select the teacher Name!",

                DepartmentId: "Please select Department!",
                CourseId: "Please select Course!"
            }
        });

        $("#DepartmentId").change(function () {
            var deptId = $("#DepartmentId").val();
            $("#TeacherId").empty();
            $("#CourseId").empty();
            $("#CourseId").append('<option value=' + "" + '>--Select Course--</option>');
            $("#TeacherId").append('<option value=' + "" + '>--Select Teacher--</option>');
            var json = { departmentId: deptId, };

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetTeachersByDepartmentId", "CourseAssignToTeacher")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {

                    $.each(data, function (key, value) {
                        //alert(key);
                        $("#TeacherId").append('<option value=' + value.Id + '>' + value.Name + '</option>');

                    });
                }
            });

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCoursesByDepartmentId", "CourseAssignToTeacher")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    $.each(data, function (key, value) {
                        $("#CourseId").append('<option value=' + value.Id + '>' + value.Code + '</option>');
                    });
                }
            });
        });

        //--------------show teacher information in textbx----
        $("#TeacherId").change(function () {
            var id = $("#TeacherId").val();

            var json = { teacherId: id, };

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetTeacherById", "CourseAssignToTeacher")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    var creditTakenTobeTaken = data.CreditTobeTaken;
                    var remainingCredit = (data.CreditTaken);
                    var creditT = creditTakenTobeTaken - remainingCredit;
                    $("#CreditTobeTaken").val(creditTakenTobeTaken);
                    $("#CreditTaken").val(creditT);
                }
            });
        });
        //-------------show Course information in textbx----
        $("#CourseId").change(function () {
            var id = $("#CourseId").val();
            var json = { courseId: id }
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetCourseById", "CourseAssignToTeacher")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    var name = data.Name;
                    var credit = data.Credit;
                    $("#Name").val(name);
                    $("#Credit").val(credit);
                }
            });
        });


    });
    </script>
}