UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Models/ClassRoom.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityManagmentSystem.Models
{
    public class ClassRoom
    {
        public int Id { get; set; }
        [Required]
        [DisplayName("Department")]
        public int DepartmentId { get; set; }
        [Required]
        [DisplayName("Course")]
        public int CourseId { get; set; }
        [Required]
        [DisplayName("Room")]
        public int RoomId { get; set; }
        [Required]
        [DisplayName("Day")]

        public int DayId { get; set; }
        [Required]
        [DisplayName("From")]
        public DateTime StartTime { get; set; }
        [Required]
        [DisplayName("To")]
        public DateTime Endtime { get; set; }
        public bool AlloctionStaus { get; set; }
    }
}

UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Controllers/ClassRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityManagmentSystem.Manager;
using UniversityManagmentSystem.Models;

namespace UniversityManagmentSystem.Controllers
{
    public class ClassRoomController : Controller
    {
        DepartmentManager departmentManager = new DepartmentManager();
        CourseManager courseManager = new CourseManager();
        RoomManager roomManager = new RoomManager();
        DayManager dayManager = new DayManager();
        ClassRoomManager classRoomManager = new ClassRoomManager();

        private List<TempClassSchedule> classRooms;
        //
        // GET: /ClassRoom/
        public ActionResult Index()
        {
            ViewBag.Departments = departmentManager.GetAll();
            classRooms = classRoomManager.GetAllClassSchedules;
            ViewBag.ClassSchedule = classRooms;
            return View();
        }


        // GET: /ClassRoom/Create
        public ActionResult Save()
        {
            List<Day> days = dayManager.GetAllDays.ToList();
            ViewBag.Days = days;
            List<Room> rooms = roomManager.GetAllRooms.ToList();
            ViewBag.Rooms = rooms;
            IEnumerable<Department> departments = departmentManager.GetAll();
            ViewBag.Departments = departments;
            ViewBag.Courses = courseManager.GetAll;
            return View();
        }

        //
        // POST: /ClassRoom/Create
        [HttpPost]
        public ActionResult Save(ClassRoom classRoom)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string message = classRoomManager.Save(classRoom);
                    ViewBag.Message = message;

                    List<Day> days = dayManager.GetAllDays.ToList();
                    ViewBag.Days = days;
                    List<Room> rooms = roomManager.GetAllRooms.ToList();
                    ViewBag.Rooms = rooms;
                    IEnumerable<Department> departments = departmentManager.GetAll().ToList();
                    ViewBag.Departments = departments;
                    IEnumerable<Course> courses = courseManager.GetAll.ToList();
                    ViewBag.Courses = courses;
                    return View();
                }
                catch
                {
                    return View();
                }
            }
            return View();
        }

        public JsonResult GetClassScheduleByDepartment(int departmentId)
        {
            var courses = courseManager.GetCourseByDepartmentId(departmentId);

            List<object> clsSches = new List<object>();

            foreach (var course in courses)
            {
                var scheduleInfo = classRoomManager.GetAllClassSchedulesByDeparmentId(departmentId, course.Id);
                if (scheduleInfo == "")
                {
                    scheduleInfo = "Not sheduled yet";
                }


                var clsSch = new
                {
                    CourseCode = course.Code,
                    CourseName = course.Name,
                    ScheduleInfo = scheduleInfo
                };
                clsSches.Add(clsSch);
            }
            return Json(clsSches, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetCoursesByDepartmentId(int departmentId)
        {
            IEnumerable<Course> courses = courseManager.GetAll;
            var courseList = courses.ToList().FindAll(c => c.DepartmentId == departmentId);
            return Json(courseList, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult UnAllocateClassRoom()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UnAllocateClassRoom(int? id)
        {
            ViewBag.Message = classRoomManager.UnAllocateClassRoom();
            return View();
        }
    }
}

UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Views/ClassRoom/Index.cshtml
@model UniversityManagmentSystem.Models.TempClassSchedule
@{
    ViewBag.Title = "Class Room Index";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
}


<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Class Schedule & Room Allocation Infromation</h3>
                    </div>
                    <div class="box-body form-horizontal">
                        <div class="form-group">
                            <label for="DepartmentId" class="col-sm-3 control-label">Select Department</label>
                            <div class="col-sm-6">
                                <select id="DepartmentId" name="DepartmentId" class="form-control">
                                    <option value="">---Select Department---</option>
                                    @foreach (var dept in ViewBag.Departments)
                                    {
                                        <option value="@dept.Id">@dept.Name</option>
                                    }
                                </select>
                            </div>
                            <div class="col-sm-3"></div>
                        </div>

                        <table id="SchduleTable" class=" table table-hover table-bordered">
                            <thead class="table-striped">
                            <tr>
                                <th style="width: 30px">Serial</th>
                                <th style="width: 150px;">Course Code</th>
                                <th style="width: 220px;">Course Name</th>
                                <th style="width: 350px;">Schedule Info</th>
                            </tr>
                            </thead>
                            <tbody></tbody>
                        </table>

                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <p>@Html.ActionLink("Allocate Class Room", "Save")</p>
                        @if (ViewBag.message != null)
                        {
                            <p style="font-size: 20px; color: blue">@ViewBag.message</p>
                        }
                    </div>
                    <!-- /.box-footer -->
                </div>
                <!-- /.box -->
            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@section scripts{
    <script>
        $(document).ready(function () {
            $("#DepartmentId").change(function () {
                $('#SchduleTable tbody').empty();
                var deptId = $("#DepartmentId").val();
                var json = { departmentId: deptId, };
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetClassScheduleByDepartment", "ClassRoom")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        $.each(data, function (key, value) {
                            key ++;
                            $("#SchduleTable tbody").append('<tr><td>' + key + '</td><td>' + value.CourseCode + '</td><td>' + value.CourseName + '</td><td>' + value.ScheduleInfo + '</td></tr>');
                        });
                    }
                });
            });
        });
    </script>
}

UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Views/ClassRoom/Save.cshtml
@model UniversityManagmentSystem.Models.ClassRoom
@{
    ViewBag.Title = "Class Room Allocate Save";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
}

<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Allocate Class Room</h3>
                    </div>
                    <div class="box-body">
                        <!-- form start -->
                        <form id="saveClassScedule" method="post" class="form-horizontal">
                            <div class=" form-group">
                                <label for="DepartmentId" class="col-sm-3 control-label">Department</label>
                                <div class="col-sm-6">
                                    <select id="DepartmentId" name="DepartmentId" class="form-control">
                                        <option value="">---Select Department---</option>
                                        @foreach (var dept in ViewBag.Departments)
                                        {
                                            <option value="@dept.Id">@dept.Name</option>
                                        }
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>

                            <div class=" form-group">
                                <label for="CourseId" class="col-sm-3 control-label">Course</label>
                                <div class="col-sm-6">
                                    <select id="CourseId" name="CourseId" class="form-control">
                                        <option value="">---Select---</option>

                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="RoomId" class="col-sm-3 control-label">Room No</label>
                                <div class="col-sm-6">
                                    <select id="RoomId" name="RoomId" class="form-control">
                                        <option value="">---Select---</option>
                                        @foreach (var room in ViewBag.Rooms)
                                        {
                                            <option value="@room.Id">@room.Name</option>
                                        }
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="DayId" class="col-sm-3 control-label">Day</label>
                                <div class="col-sm-6">
                                    <select id="DayId" name="DayId" class="form-control">
                                        <option value="">---Select---</option>
                                        @foreach (var day in ViewBag.Days)
                                        {
                                            <option value="@day.Id">@day.Name</option>
                                        }
                                    </select>
                                </div>
                                <div class="col-sm-3">
                                </div>
                            </div>

                        <div class="form-group">
                            <label for="StartTime" class="col-sm-3 control-label">Start Time</label>
                        <div class="col-sm-6">
                            <div class="bootstrap-timepicker">
                                <input type="text" id="StartTime" class="form-control" name="StartTime" />
                            </div>
                            <div class="col-sm-3">
                            </div>
                        </div>
                        </div>
                            
                                <div class="form-group">
                                    <label for="Endtime" class="col-sm-3 control-label">End Time</label>
                                    <div class="col-sm-6">
                                        <div class="bootstrap-timepicker">
                                            <input type="text" id="Endtime" class="form-control" name="Endtime" />
                                        </div>
                                    <div class="col-sm-3">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-3"></div>
                                <div class="col-sm-6">
                                    <button type="submit" class="btn btn-info pull-left">Save</button>
                                </div>
                                <div class="col-sm-3"></div>
                            </div>
                        </form>
                    </div>                      <!-- /.box-body -->
                    <div class="box-footer">
                        <p>@Html.ActionLink("View Class Schedule", "Index", "ClassRoom")</p>
                        @if (ViewBag.Message != null)
                        {
                            <p style="font-size: 20px; color: blue">@ViewBag.Message</p>
                        }
                    </div>
                    <!-- /.box-footer -->
                    <!-- form end -->
                </div>
                <!-- /.box -->
            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->

    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->
@section scripts{
 
    <script src="~/Scripts/jquery.validate.js"></script>
  
    <script>
        $(document).ready(function () {

            $("#saveClassScedule").validate({
                rules: {
                    CourseId: "required",
                    RoomId: "required",
                    DayId: "required",
                    StartTime: "required",
                    DepartmentId: "required",
                    Endtime: "required"

                },
                messages: {
                    CourseId: "Please Select  Course!",

                    RoomId: "Please Select room!",
                    DayId: "Please Select day!",
                    StartTime:"Select Start time!",
                    DepartmentId: "Please select department!",
                    Endtime: "Please select End time!"
                }
            });

            $("#DepartmentId").change(function () {
                var deptId = $("#DepartmentId").val();
                $("#CourseId").empty();
                $("#CourseId").append('<option value="">---Select Course---</option>');

                var json = { departmentId: deptId, };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetCoursesByDepartmentId", "ClassRoom")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {
                        //alert(data);
                        $.each(data, function (key, value) {
                            //alert(key);
                            $("#CourseId").append('<option value=' + value.Id + '>' + value.Code + '</option>');

                        });
                    }
                });


            });
            $("#StartTime").timepicker({
                showInputs: false
            });

            $("#Endtime").timepicker({
                showInputs: false
            });

            //Timepicker
            $(".timepicker").timepicker({
                showInputs: false
            });

        });
    </script>
}

UniversityManagmentSystem-17.02.2018/UniversityManagmentSystem/Views/ClassRoom/UnAllocateClassRoom.cshtml
@{
    ViewBag.Title = "UnAllocate Class Room";
    Layout = "~/Views/Shared/Home_Layout.cshtml";
}
<style>
    .example-modal .modal {
        position: relative;
        top: auto;
        bottom: auto;
        right: auto;
        left: auto;
        display: block;
        z-index: 1;
    }

    .example-modal .modal {
        background: transparent !important;
    }
</style>
<style>
    .example-modal .modal {
        position: relative;
        top: auto;
        bottom: auto;
        right: auto;
        left: auto;
        display: block;
        z-index: 1;
    }

    .example-modal .modal {
        background: transparent !important;
    }
</style>
<div class="content-wrapper">
    <section class="content">
        <div class="example-modal">
            <div class="modal modal-info">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Unallocate Class Room</h4>
                        </div>
                        <div class="modal-body">
                            <p>You Want To Unallocate All Class Room?</p>
                            @if (ViewBag.Message != null)
                            {
                                <p>@ViewBag.Message</p>
                            }
                        </div>
                        <div class="modal-footer">
                            <form method="POST">
                                <input type="submit" class="btn btn-outline pull-left" data-dismiss="modal" value="Unallocate Rooms" data-confirm="Are you sure to Unallocate All Class Room?" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
@section scripts{
    <script>
        $(document).ready(function () {
            jQuery('[data-confirm]').click(function (e) {
                if (!confirm(jQuery(this).attr("data-confirm"))) {
                    e.preventDefault();
                }
            });
        });
    </script>
}